name: snail_db
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/evandersondev/snail_db

environment:
  sdk: ^3.0.5

dependencies:
  uuid: ^4.3.3
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
